# Generated by Django 2.1.4 on 2019-08-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazasignup', '0009_auto_20190728_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='bazasignupautoapprovalfailreason',
            name='reason_type',
            field=models.CharField(choices=[('no_email', 'no_email'), ('no_phone', 'no_phone'), ('non_unique_email', 'non_unique_email'), ('non_unique_phone', 'non_unique_phone'), ('no_twilio_data', 'no_twilio_data'), ('no_geoip_data', 'no_geoip_data'), ('twilio_vs_userinput_address_range_exceed', 'twilio_vs_userinput_address_range_exceed'), ('geoip_vs_userinput_address_range_exceed', 'geoip_vs_userinput_address_range_exceed'), ('no_distance_fetched_twilio_vs_userinput', 'no_distance_fetched_twilio_vs_userinput'), ('no_distance_fetched_geoip_vs_userinput', 'no_distance_fetched_geoip_vs_userinput')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='historicalbazasignupautoapprovalfailreason',
            name='reason_type',
            field=models.CharField(choices=[('no_email', 'no_email'), ('no_phone', 'no_phone'), ('non_unique_email', 'non_unique_email'), ('non_unique_phone', 'non_unique_phone'), ('no_twilio_data', 'no_twilio_data'), ('no_geoip_data', 'no_geoip_data'), ('twilio_vs_userinput_address_range_exceed', 'twilio_vs_userinput_address_range_exceed'), ('geoip_vs_userinput_address_range_exceed', 'geoip_vs_userinput_address_range_exceed'), ('no_distance_fetched_twilio_vs_userinput', 'no_distance_fetched_twilio_vs_userinput'), ('no_distance_fetched_geoip_vs_userinput', 'no_distance_fetched_geoip_vs_userinput')], default='', max_length=100),
        ),
    ]
